# Exception handling with else block

try :
    print('Hello')

except :
    print('something went wrong')

else :
    print('Nothing is went wrong')

# In this ex, the 'try' block does not generate any error.
